version: '3.0'
volumes:
  lake_pgdata:

networks:
  lake_postgres:
    driver: bridge

services:
  lake_postgres:
    image: openmaptiles/postgis
    # Use "command: postgres -c jit=off" for PostgreSQL 11+ because of slow large MVT query processing
    volumes:
      - lake_pgdata:/var/lib/postgresql/data
    networks:
      - lake_postgres
    ports:
      - "5432"
    env_file: .env-postgres
    
  import-osm:
    build: src/import-osm
    networks:
      - lake_postgres
    volumes:
     - ./data:/import
    env_file: .env
    
  export-shapefile:
    build: src/export-shapefile
    env_file: .env
    networks:
      - lake_postgres
    volumes:
     - ./data:/data

  calculate-centerlines:
    build: src/calculate-centerlines
    networks:
      - lake_postgres
    volumes:
     - ./data:/data
